nome = input('Digite o seu nome: ')
nomeMaiusculo = nome.upper()
print(nomeMaiusculo)
nomeMinusculo = nome.lower()
print(nomeMinusculo)
nomeSemespaco = nome.replace(' ','')
print('A quantidade de caracteres sem espaço é:',len(nomeSemespaco))
novoNome = nome.split()
print(len(novoNome[0]))